name: Generate Heatmap
on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 运行
  workflow_dispatch:  # 允许手动触发
jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 添加此权限以允许提交和推送
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install jq
        run: sudo apt-get install jq
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests svgwrite
      - name: Get Gist content
        id: gist
        env:
          GIST_URL: ${{ secrets.GIST_URL }}  # 从 GitHub Secrets 中获取 Gist ID
        run: |
          # 获取JSON文件内容
          JSON_DATA=$(curl -s "$GIST_URL")
          
          # 使用jq解析并导出变量
          echo "USER_VID=$(echo $JSON_DATA | jq -r '.vid')" >> $GITHUB_ENV
          echo "REQUEST_BODY=$(echo $JSON_DATA | jq -r '.requestBody')" >> $GITHUB_ENV
          echo "REQUEST_HEADERS=$(echo $JSON_DATA | jq -r '.headers')" >> $GITHUB_ENV
      - name: Generate heatmap
        env:
          USER_VID: ${{ env.USER_VID }}
          REQUEST_BODY: ${{ env.REQUEST_BODY }}
          REQUEST_HEADERS: ${{ env.REQUEST_HEADERS }}
          START_YEAR: ${{ vars.START_YEAR }}
          END_YEAR: ${{ vars.END_YEAR }}
          NAME: ${{ vars.NAME }}
          TRACK_COLOR: ${{ vars.TRACK_COLOR }}
          TRACK_SPECIAL1_COLOR: ${{ vars.TRACK_SPECIAL1_COLOR }}
          TRACK_SPECIAL2_COLOR: ${{ vars.TRACK_SPECIAL2_COLOR }}
          TRACK_SPECIAL3_COLOR: ${{ vars.TRACK_SPECIAL3_COLOR }}
          TRACK_SPECIAL4_COLOR: ${{ vars.TRACK_SPECIAL4_COLOR }}
          DEFAULT_DOM_COLOR: ${{ vars.DEFAULT_DOM_COLOR }}
          TEXT_COLOR: ${{ vars.TEXT_COLOR }}
          TITLE_COLOR: ${{ vars.TITLE_COLOR }}
          YEAR_TXT_COLOR: ${{ vars.YEAR_TXT_COLOR }}
          MONTH_TXT_COLOR: ${{ vars.MONTH_TXT_COLOR }}
        run: python heatmap.py
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "action@github.com"
          git add heatmap.svg
          git commit -m "Update heatmap [skip ci]" || echo "nothing to commit"
          git push || echo "nothing to push"
